# -*- coding: utf-8 -*-
"""SimpleLinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1marr83a2T_maH3-Y7VycIZx8mOuEed1g

#Task-2 To Explore Supervised Machine Learning

#Importing all the required Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""#Reading Data From the Remote Link"""

url ="http://bit.ly/w-data"
s_data = pd.read_csv(url)
print(s_data.head(10))

"""#Plotting the Distribution of Scores"""

s_data.plot(x='Hours', y='Scores', style='o')
plt.title('Hours vs Percentage')
plt.xlabel('Hours Studied')
plt.ylabel('Percentage Score')
plt.show()

"""#Data Preprocessing"""

X = s_data.iloc[:, :-1].values
y = s_data.iloc[:, 1].values

"""#Training of Data"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=0) 
print("Training is done")

"""#Simple Linear Regression Model"""

from sklearn.linear_model import LinearRegression 
regressor = LinearRegression()
regressor.fit(X_train, y_train)

"""#Prediction"""

print(X_test)
y_pred = regressor.predict(X_test)
print(y_pred)

df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(df)

hours =[[9.25]]

"""#Final Problem Prediction"""

own_pred = regressor.predict(hours)
print(own_pred)

"""#Accuracy Check"""

from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))